version: '2'

services:
  web:
    build: .
    container_name: furnipop_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - furninet

  mysql:
    image: mysql:5.7
    container_name: ${MYSQL_HOST}
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 30009:3306
    volumes:
      - ./data/db/mysql:/var/lib/mysql
    networks:
      - furninet

networks:
  furninet:
    external: true