version: '2'

services:
  web:
    build: .
    container_name: furnipop_api
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "8000:80"
    networks:
      - lasenia-shared

networks:
  lasenia-shared:
    external: true